.gitignore
server/.gitignore
server/githubsrm/apis/open_views.py
server/githubsrm/core/settings.py
server/githubsrm/core/urls.py
server/poetry.lock
server/pyproject.toml
server/requirements.txt

Static site rendering of Next.js fixed.
Credits to: @Aradhya-Tripathi 

Fix Static Site Rendering

---

.gitignore
deploy.sh
server/.gitignore
server/githubsrm/apis/open_views.py
server/githubsrm/core/settings.py
server/githubsrm/core/urls.py
server/poetry.lock
server/pyproject.toml
server/requirements.txt

Deploy Scripts

---

server/githubsrm/apis/open_views.py
server/githubsrm/apis/utils.py
server/githubsrm/core/settings.py
server/githubsrm/core/urls.py

Route handling and 404 rendering

Conditional route handling  

---

client/components/team/member.tsx
client/services/api.tsx
client/utils/interfaces.ts

🚸 member designation

---

.github/PULL_REQUEST_TEMPLATE.md
.travis.yml
deploy.sh
run.sh
run_tests.sh
server/githubsrm/apis/models.py
server/githubsrm/apis/open_views.py
server/githubsrm/apis/throttle.py
server/githubsrm/apis/utils.py
server/githubsrm/core/settings.py

Removed throttling from get routes

Removed throttle from get requests

---

server/poetry.lock
server/requirements.txt

Update requirements with pymongo

🔧 update config

---

client/components/index/benefits.tsx
client/components/index/hero.tsx
client/components/join-us/maintainer/maintainer.tsx
client/components/shared/footer.tsx
client/pages/404.tsx
client/pages/500.tsx
client/pages/_document.tsx
client/pages/contact-us.tsx
client/pages/join-us/contributor.tsx
client/pages/join-us/index.tsx
client/pages/join-us/maintainer/existing-project.tsx
client/pages/join-us/maintainer/index.tsx
client/pages/join-us/maintainer/new-project.tsx
client/pages/projects.tsx
client/pages/team.tsx

Increased lighthouse audits scores.
enhancement 

🔍 improve lighthouse audits

---

server/githubsrm/administrator/issue_jwt.py
server/githubsrm/administrator/middleware.py
server/githubsrm/administrator/perms.py
server/githubsrm/administrator/views.py

Added response support for middleware, added comments showcasing middleware use.
Fixes #28 

Dev at auth

---

server/githubsrm/administrator/utils.py
server/githubsrm/administrator/views.py
server/githubsrm/apis/__init__.py
server/githubsrm/apis/checks_models.py
server/githubsrm/apis/models.py

Single project get route was implemented
Fixes #22  

Resolve Single project get route

---

server/githubsrm/core/settings.py
server/githubsrm/core/urls.py
server/githubsrm/maintainer/admin.py
server/githubsrm/maintainer/apps.py
server/githubsrm/maintainer/models.py
server/githubsrm/maintainer/tests.py
server/githubsrm/maintainer/urls.py
server/githubsrm/maintainer/utils.py
server/githubsrm/maintainer/views.py

Maintainer portal app
Fixes #32 

🎉 maintainer app

---

server/githubsrm/apis/checks_models.py
server/githubsrm/maintainer/__init__.py
server/githubsrm/maintainer/models.py
server/githubsrm/maintainer/utils.py

single project get route along with some fixes
Fixes #36

Maintainer SingleProject get route

---

server/githubsrm/maintainer/models.py

🚑  model error

---

server/githubsrm/maintainer/utils.py

WIP pagination to send all projects. need to add auth for projects

🚧 maintainer get projects route

---

server/githubsrm/apis/models.py
server/githubsrm/maintainer/definitions.py
server/githubsrm/maintainer/models.py
server/githubsrm/maintainer/views.py

Added maintainer post route, updated old code and added definitions.
Fixes #48 

at-maintainer

---

server/githubsrm/maintainer/definitions.py
server/githubsrm/maintainer/models.py
server/githubsrm/maintainer/urls.py
server/githubsrm/maintainer/views.py

✨  maintainer auth

---

server/githubsrm/administrator/views.py
server/githubsrm/apis/utils.py

Added basic email logic. Main email logic to be changed

Added basic email logic

---

server/githubsrm/maintainer/definitions.py
server/githubsrm/maintainer/utils.py

Check with JWT
Fixes #52 
- X] I have performed a self-review of my own code

✨ JWT checks

---

server/githubsrm/administrator/views.py
server/githubsrm/apis/utils.py

🚧 Email fixes

---

server/githubsrm/administrator/models.py
server/githubsrm/administrator/views.py

Patch fixing emailing service (templates to be updated)

At email fix

---

server/githubsrm/administrator/issue_jwt.py
server/githubsrm/administrator/middleware.py
server/githubsrm/administrator/urls.py
server/githubsrm/administrator/utils.py
server/githubsrm/administrator/views.py

Added role verification, added maintainer protected routes to protected list, and made projects approved pagination.

At auth fixes

---

server/githubsrm/administrator/definitions.py
server/githubsrm/administrator/models.py
server/githubsrm/administrator/views.py
server/githubsrm/apis/checks_models.py
server/githubsrm/apis/open_views.py
server/githubsrm/maintainer/models.py
server/githubsrm/maintainer/utils.py

Changed password collection, this is a breaking change that needs to be addressed in maintainer login @saxenabhishek .
fixed reset password route

refactor: changed password storage

---

server/githubsrm/administrator/definitions.py
server/githubsrm/administrator/views.py
server/githubsrm/maintainer/models.py
server/githubsrm/maintainer/views.py

♻️ maintainer login

---

server/githubsrm/administrator/issue_jwt.py
server/githubsrm/administrator/models.py
server/githubsrm/administrator/views.py
server/githubsrm/apis/utils.py
server/githubsrm/maintainer/definitions.py
server/githubsrm/maintainer/models.py
server/githubsrm/maintainer/urls.py
server/githubsrm/maintainer/utils.py
server/githubsrm/maintainer/views.py

Pagination of maintainer and contributor on get single project

✨ Pagination on contributor and maintainer

---

server/githubsrm/maintainer/definitions.py
server/githubsrm/maintainer/models.py
server/githubsrm/maintainer/views.py

Json response missing `data`, Switch variables form reset to set 
@sakshi-choudhary

🚑  Password change email

---

server/githubsrm/administrator/views.py
server/githubsrm/apis/models.py
server/githubsrm/apis/open_views.py
server/githubsrm/maintainer/models.py
server/githubsrm/maintainer/utils.py
server/githubsrm/maintainer/views.py

emails templates from 8 - 10
it has not been

Aks email integration

---

server/githubsrm/administrator/utils.py
server/githubsrm/maintainer/utils.py

changed return types of project pagination. 
Fixes #77 
- [z] My code follows the style guidelines of this project
- [z] I have performed a self-review of my own code
- [z] I have commented on my code, particularly in hard-to-understand areas
- [z] My changes generate no new warnings
- [z] I have added tests that prove my fix is effective or that my feature works
- [z] New and existing unit tests pass locally with my changes

🎨 Changed return types fixes #77

---

server/githubsrm/maintainer/utils.py
server/githubsrm/maintainer/views.py

- Pagination format fix on maintainer single project GET
- name change on set password route
close #76 
Return format with config
```json
{
"_id": "XXXXXXXX",
"project_url": "",
"description": "Some text",
"tags": [
"Tag 1",
"Tag 1",
"Tag 1",
"Tag 1"
],
"is_admin_approved": false,
"project_name": "some name",
"private": true,
"maintainer_id": [
"XXXXXXXX"
],
"maintainer": [
{
"_id": "XXXXXXXX",
"name": "Jane Doe",
"email": "Jane Doe@gmail.com",
"github_id": "xyz",
"srm_email": "XX###@srmist.edu.in",
"reg_number": "RAXXXXXXXXXXX",
"branch": "XX-XX",
"project_id": "XXXXXXX",
"is_admin_approved": true,
"time_stamp": "2021-XX-XX"
}
],
"contributor": [],
"maintainerHasNextPage": false,
"contributorHasNextPage": false
}
```

Dev aks hot fixes

---

client-landing/.env.example
client-landing/next.config.js
client-portals/.env.example
client-portals/components/admin/dashboard/accepted-projects/accepted-projects-cards.tsx
client-portals/components/admin/dashboard/index.tsx
client-portals/components/admin/dashboard/projectVisibilityPopup.tsx
client-portals/components/admin/login.tsx
client-portals/components/admin/register.tsx
client-portals/components/maintainer/dashboard/dashboard.tsx
client-portals/components/shared/navbar.tsx
client-portals/context/authContext.tsx
client-portals/next.config.js
client-portals/package.json
client-portals/pages/maintainer/dashboard/[slug].tsx
client-portals/services/api.tsx
client-portals/utils/constants.tsx
client-portals/utils/icons/logout.tsx
client-portals/utils/icons/navbarBurger.tsx
client-portals/utils/interfaces.ts

WIP: Portal (client)

---

server/githubsrm/administrator/utils.py
server/githubsrm/administrator/views.py

moved logic to utils and added additional error responses.

♻️ Refactored admin project post

---

client-portals/components/admin/dashboard/accepted-projects/accepted-projects-cards.tsx
client-portals/pages/maintainer/dashboard/[slug].tsx

Portal (client)

---

client/client-landing/services/api.tsx

🐛 minor API call bugs

---

server/githubsrm/apis/open_views.py

🔥 Removed get all route

---

server/githubsrm/administrator/views.py
server/githubsrm/apis/open_views.py
server/githubsrm/apis/templates/12.html
server/githubsrm/apis/utils.py

Added contributor notification

Contributor Notification

---

server/githubsrm/administrator/views.py
server/githubsrm/apis/utils.py

Maintainer notification

---

server/githubsrm/administrator/views.py

✏️ Email array.

---

server/githubsrm/administrator/definitions.py
server/githubsrm/administrator/middleware.py
server/githubsrm/administrator/models.py
server/githubsrm/administrator/views.py
server/githubsrm/maintainer/definitions.py
server/githubsrm/maintainer/models.py
server/githubsrm/maintainer/views.py

Removing maintainer, contributor. 
Fixes #99 

Added Removal 

---

README.md

📄 Updated readme according to **v2.5.0**

📄 Update readme

---

Procfile
requirements.txt
server/githubsrm/administrator/definitions.py
server/githubsrm/administrator/issue_jwt.py
server/githubsrm/administrator/middleware.py
server/githubsrm/administrator/models.py
server/githubsrm/administrator/utils.py
server/githubsrm/administrator/views.py
server/githubsrm/maintainer/definitions.py
server/githubsrm/maintainer/models.py
server/githubsrm/maintainer/views.py

This is a critical hotfix enforcing role based authentication

Enforced roles

---

server/githubsrm/administrator/views.py
server/poetry.lock
server/pyproject.toml
server/run_backend_tests.sh
server/tests/test_admin.py
server/tests/test_apis.py
server/tests/test_full_flow.py
server/tests/test_maintainer.py

✅ Added basic tests

---

server/githubsrm/administrator/views.py
server/githubsrm/apis/open_views.py
server/githubsrm/core/settings.py
server/githubsrm/maintainer/views.py

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
- Firmware version:
- Hardware:
- Toolchain:
- SDK:

🔧  Moved recaptcha to middleware

---

Procfile

down to 1 worker 
Fixes # (issue)

Staging test

---

client/client-portals/pages/admin/index.tsx
server/githubsrm/administrator/definitions.py
server/githubsrm/administrator/models.py
server/githubsrm/administrator/views.py

Typos and maintainer rejection 
maintainers were added and removed multiple times under multiple circumstance

Staging maintainer reject

---

README.md
client/client-landing/package.json
client/client-landing/pages/_app.tsx
client/client-portals/package.json
client/client-portals/pages/404.tsx
client/client-portals/pages/500.tsx
client/client-portals/pages/_app.tsx
client/client-portals/pages/maintainer/dashboard/[slug].tsx
client/client-portals/utils/icons/404.tsx
client/client-portals/utils/icons/500.tsx
client/client-portals/utils/icons/index.tsx
client/package.json
client/yarn.lock
server/githubsrm/administrator/definitions.py
server/githubsrm/administrator/middleware.py
server/githubsrm/administrator/models.py
server/githubsrm/administrator/utils.py
server/githubsrm/administrator/views.py
server/githubsrm/apis/definitions.py
server/githubsrm/apis/templates/13.html
server/githubsrm/apis/templates/14.html
server/githubsrm/apis/templates/15.html
server/githubsrm/apis/utils.py
server/githubsrm/core/settings.py
server/githubsrm/maintainer/models.py
server/githubsrm/maintainer/views.py
server/pyproject.toml
server/run_backend_tests.sh

- 404 ErrorPage
- 500 Error Page
- Disable Sentry on Dev
- Add email templates
- Server boot from test script
- Rejection emails
Fixes #117 
Fixes #118 
Fixes #119 

✨ Final touches

---

client/client-portals/pages/_app.tsx
client/client-portals/styles/tailwind.styles.css
client/client-portals/utils/functions/toast.tsx

💄 🍻 css fixes dont end :(

---

client/client-portals/components/shared/navbar.tsx

💄 add navbar role

---

client/client-portals/components/maintainer/dashboard/dashboard.tsx
client/client-portals/services/api.tsx

🚑 critical hotfix : logout bugs

---

client/client-portals/components/maintainer/dashboard/dashboard.tsx
client/client-portals/pages/admin/dashboard/[slug].tsx
client/client-portals/pages/maintainer/dashboard/[slug].tsx
client/client-portals/services/api.tsx

Pagination & Loader Bug Fixes

---

server/run_backend_tests.sh
server/tests/test_maintainer.py

Co-authored-by: Riju Mukherjee <rmukh561@gmail.com>
Added single project pagination tests.

✅ Added single project pagination tests.

---

client/client-portals/pages/admin/dashboard/accepted-projects/[slug].tsx

Fix Loader on Accepted Projects Page.
UI Fixes

💄 Loader Fixes

---

server/githubsrm/apis/utils.py

removed httpx client to fix a bug

🐛 removed redundant libs

---

server/githubsrm/apis/open_views.py

Minor return type standardised

🩹 standardised return values

---

server/githubsrm/apis/aws.py

BotoService wrapper for lambdas

✨ Lambda wrapper

---

server/githubsrm/apis/aws.py

Aks generic lambda

---

server/githubsrm/apis/definitions.py
server/githubsrm/apis/open_views.py

- Added feature to trigger sns on a project port

✨ Trigger sns on project porting

---

server/githubsrm/administrator/definitions.py
server/githubsrm/administrator/models.py
server/githubsrm/administrator/tests.py
server/githubsrm/administrator/views.py
server/githubsrm/apis/__init__.py
server/githubsrm/apis/aws.py
server/githubsrm/apis/definitions.py
server/githubsrm/apis/models.py
server/githubsrm/apis/open_views.py
server/githubsrm/apis/utils.py
server/githubsrm/maintainer/models.py
server/githubsrm/maintainer/tests.py
server/githubsrm/maintainer/utils.py

changed schema in maintainer application and project approval.

refactor: changed schema and re-structured AWS service

---

server/githubsrm/administrator/views.py
server/githubsrm/apis/open_views.py
server/githubsrm/core/__init__.py
server/githubsrm/core/settings.py
server/githubsrm/maintainer/views.py

🚑 Fixed throttling

---

server/githubsrm/administrator/models.py
server/githubsrm/administrator/views.py
server/githubsrm/maintainer/errors.py
server/githubsrm/maintainer/models.py
server/githubsrm/maintainer/views.py
server/tests/__init__.py
server/tests/test_admin.py
server/tests/test_apis.py
server/tests/test_full_flow.py
server/tests/test_maintainer.py
server/tests/test_schema.py

Updated tests and refactored code

Updated tests

---

server/githubsrm/core/middleware.py

Accepting non-json in admin/register route

fix(minor): accepting non json in admin/register

---

server/githubsrm/apis/templates/email_statics.json
server/githubsrm/core/aws.py
server/githubsrm/core/utils.py

refactoring email module now evaluates kwargs send to it and caches the location of templates folder while maintaining one dict for specifics.
Update: all tests are passing 👍🏻

♻️ aws email

---

.github/workflows/run_tests.yml
server/githubsrm/administrator/apps.py
server/githubsrm/administrator/errors.py
server/githubsrm/administrator/models.py
server/githubsrm/administrator/urls.py
server/githubsrm/administrator/utils.py
server/githubsrm/administrator/views.py
server/githubsrm/apis/apps.py
server/githubsrm/apis/checks_models.py
server/githubsrm/apis/open_views.py
server/githubsrm/apis/urls.py
server/githubsrm/apis/utils.py
server/githubsrm/core/__init__.py
server/githubsrm/core/asgi.py
server/githubsrm/core/errorfactory.py
server/githubsrm/core/settings.py
server/githubsrm/core/urls.py
server/githubsrm/core/utils.py
server/githubsrm/core/wsgi.py
server/githubsrm/maintainer/__init__.py
server/githubsrm/maintainer/apps.py
server/githubsrm/maintainer/errors.py
server/githubsrm/maintainer/models.py
server/githubsrm/maintainer/urls.py
server/githubsrm/maintainer/utils.py
server/githubsrm/maintainer/views.py
server/githubsrm/manage.py
server/poetry.lock
server/pyproject.toml
server/requirements.txt

* Auto-exception handling on errors occurring at API level

feat: Added API-Level error handling

---

client/client-landing/components/shared/input.tsx
client/client-landing/utils/constants.tsx
client/client-portals/components/admin/dashboard/academic-year.tsx
client/client-portals/components/admin/dashboard/index.tsx
client/client-portals/components/shared/button.tsx
client/client-portals/utils/interfaces.ts

- Change button component and make the styling dynamic
- Add close button to the academic year modal

:lipstick: Optimise Admin Portal

---

server/githubsrm/core/aws.py

Changed erroneous variable name while logging lambda errors.

fix: fixed variable name while logging

---

server/run_backend_tests.sh
server/tests/__init__.py
server/tests/test_admin.py
server/tests/test_apis.py
server/tests/test_full_flow.py
server/tests/test_maintainer.py
server/tests/test_schema.py

♻️ Refactor tests

---

lambdas/create-project/src/services/github.ts
lambdas/create-project/src/services/parsers.ts

Fixes #195 
- Removing control chars like `\n` or `\r` from the description as per GitHub API docs.

Feat: add project description parsing

---

server/githubsrm/core/models.py

fix: uuid generation

---

server/githubsrm/apis/models.py

Removed maintainer Id and team slug from get route

refactor: removed sensitive details in maintainer's get route

---

server/githubsrm/administrator/urls.py
server/githubsrm/administrator/views.py
server/githubsrm/apis/open_views.py
server/githubsrm/apis/urls.py
server/githubsrm/maintainer/urls.py
server/githubsrm/maintainer/views.py
server/tests/test_schema.py

* Removed class views where functional views made more sense.
* Changed project approval tests to fit with the current project sechma

refactor: moved to functional views & fixed project approval tests
